- name: remove the old mysql package
  yum: name=mysql-libs state=absent

- name: install mysql dependency package
  yum: name={{ item }} state=present
  with_items:
        - libaio*
        - perl-ExtUtils-Embed

- name: install libselinux-python for ansible
  yum: name=libselinux-python state=present

- name: copy shell script to nodes
  copy: src={{ item }} dest=/tmp/
  with_items:
         - mysql_init_db.sh
         - mysql_security.sh

- name: install mysql used rpm from alibaichuang
  yum: name={{ item }} state=present
  with_items:
         - '{{ mysql_server_url }}'
         - '{{ mysql_devel_url }}'
         - '{{ mysql_client_url }}'

- name: copy the mysql my.cnf file 
  template: src=my.cnf.j2 dest=/etc/my.cnf

- name: copy the hosts file
  template: src=hosts.j2 dest=/etc/hosts backup=yes 

- name: init the mysql db
  shell: sh /tmp/mysql_init_db.sh

- name: skip mysql password
  shell: nohup /usr/bin/mysqld_safe --skip-grant-tables >/dev/null 2>&1 &

- name: mysql security setting 
  shell: sh /tmp/mysql_security.sh

- name: link mysql.sock
  file: src={{ mysql_datadir  }}/mysql.sock path=/var/lib/mysql/mysql.sock state=link

- name: restart mysql service 
  service: name=mysql state=restarted
