- name: remove the old mysql package
  yum: name=mysql-libs state=absent

- name: install mysql dependency package
  yum: name={{ item }} state=present
  with_items:
        - libaio*
        - perl-ExtUtils-Embed

- name: install libselinux-python for ansible
  yum: name=libselinux-python state=present

- name: copy shell script to nodes
  copy: src={{ item }} dest=/tmp/
  with_items:
         - mysql_init_db.sh
         - mysql_security.sh

- name: install mysql used rpm from alibaichuang
  yum: name={{ item }} state=present
  with_items:
        - http://software1.file.alimmdn.com/mysql5.6_x64/MySQL-server-5.6.15-1.el6.x86_64.rpm
        - http://software1.file.alimmdn.com/mysql5.6_x64/MySQL-devel-5.6.15-1.el6.x86_64.rpm
        - http://software1.file.alimmdn.com/mysql5.6_x64/MySQL-client-5.6.15-1.el6.x86_64.rpm

- name: copy the mysql my.cnf file 
  copy: src=my.cnf dest=/etc/my.cnf

- name: copy the hosts file
  template: src=hosts.j2 dest=/etc/hosts backup=yes 

- name: init the mysql db
  shell: sh /tmp/mysql_init_db.sh

- name: skip mysql password
  shell: nohup /usr/bin/mysqld_safe --skip-grant-tables >/dev/null 2>&1 &

- name: mysql security setting 
  shell: sh /tmp/mysql_security.sh

- name: restart mysql service 
  service: name=mysql state=restarted
