---
- hosts: shop_admin
  gather_facts: no

  tasks:

  - name: add limited lines
    lineinfile: dest=/etc/security/limits.conf line={{ item }}
    with_items:
          - '*    soft    nproc   65536'
          - '*    hard    nproc   65536'
          - '*    soft    nofile  65536'
          - '*    hard    nofile  65536'

