- name: install gcc
  yum: name=gcc state=installed
- name: copy file to client
  copy: src={{ item }} dest=/tmp/
  with_items:
     - redis-3.2.8.tar.gz
     - install_redis.sh
     - optimize_redis.sh
- name: optimize redis
  shell: /bin/bash /tmp/optimize_redis.sh
- name: install redis
  shell: /bin/bash /tmp/install_redis.sh
- name: start redis
  shell: sudo -u redis /usr/local/bin/redis-server /data/redis/redis.conf
- name: copy redis script to init.d
  copy: src=redis dest=/etc/init.d/redis mode=0755 backup=yes
- name: add sudo service for redis
  lineinfile: 
        dest: /etc/sudoers
        state: present
        regexp: '^root     ALL=(ALL)'
        insertbefore: "^## Allows members of the 'sys'"
        line: "{{ item }}"
        validate: 'visudo -cf %s'
  with_items:
         - 'redis        ALL=(ALL)       NOPASSWD:/etc/init.d/redis start'
         - 'redis        ALL=(ALL)       NOPASSWD:/etc/init.d/redis status'
         - 'redis        ALL=(ALL)       NOPASSWD:/etc/init.d/redis stop'
  tags:
     sudo
- name: add redis on boot
  shell: echo 'sudo -u redis /usr/local/bin/redis-server /data/redis/redis.conf' >> /etc/rc.local
  tags:
     boot    
